namespace PortalWebEconomiza.Utils
{
    // Classe para o objeto (usado no dropdown)
    public class Municipio
    {
        public int CodigoIBGE { get; set; }
        public string Nome { get; set; }
    }

    // Classe estática com os dados
    public static class MunicipioData
    {
        public static List<Municipio> GetMunicipios() => new List<Municipio>
        {
            new Municipio { CodigoIBGE = 2700102, Nome = "Água Branca" },
            new Municipio { CodigoIBGE = 2700201, Nome = "Anadia" },
            new Municipio { CodigoIBGE = 2700300, Nome = "Arapiraca" },
            new Municipio { CodigoIBGE = 2700409, Nome = "Atalaia" },
            new Municipio { CodigoIBGE = 2700508, Nome = "Barra de Santo Antônio" },
            new Municipio { CodigoIBGE = 2700607, Nome = "Barra de São Miguel" },
            new Municipio { CodigoIBGE = 2700706, Nome = "Batalha" },
            new Municipio { CodigoIBGE = 2700805, Nome = "Belém" },
            new Municipio { CodigoIBGE = 2700904, Nome = "Belo Monte" },
            new Municipio { CodigoIBGE = 2701001, Nome = "Boca da Mata" },
            new Municipio { CodigoIBGE = 2701100, Nome = "Branquinha" },
            new Municipio { CodigoIBGE = 2701209, Nome = "Cacimbinhas" },
            new Municipio { CodigoIBGE = 2701308, Nome = "Cajueiro" },
            new Municipio { CodigoIBGE = 2701357, Nome = "Campestre" },
            new Municipio { CodigoIBGE = 2701407, Nome = "Campo Alegre" },
            new Municipio { CodigoIBGE = 2701506, Nome = "Campo Grande" },
            new Municipio { CodigoIBGE = 2701605, Nome = "Canapi" },
            new Municipio { CodigoIBGE = 2701704, Nome = "Capela" },
            new Municipio { CodigoIBGE = 2701803, Nome = "Carneiros" },
            new Municipio { CodigoIBGE = 2701902, Nome = "Chã Preta" },
            new Municipio { CodigoIBGE = 2702009, Nome = "Coité do Nóia" },
            new Municipio { CodigoIBGE = 2702108, Nome = "Colônia Leopoldina" },
            new Municipio { CodigoIBGE = 2702207, Nome = "Coqueiro Seco" },
            new Municipio { CodigoIBGE = 2702306, Nome = "Coruripe" },
            new Municipio { CodigoIBGE = 2702355, Nome = "Craíbas" },
            new Municipio { CodigoIBGE = 2702405, Nome = "Delmiro Gouveia" },
            new Municipio { CodigoIBGE = 2702504, Nome = "Dois Riachos" },
            new Municipio { CodigoIBGE = 2702553, Nome = "Estrela de Alagoas" },
            new Municipio { CodigoIBGE = 2702603, Nome = "Feira Grande" },
            new Municipio { CodigoIBGE = 2702702, Nome = "Feliz Deserto" },
            new Municipio { CodigoIBGE = 2702801, Nome = "Flexeiras" },
            new Municipio { CodigoIBGE = 2702900, Nome = "Girau do Ponciano" },
            new Municipio { CodigoIBGE = 2703007, Nome = "Ibateguara" },
            new Municipio { CodigoIBGE = 2703106, Nome = "Igaci" },
            new Municipio { CodigoIBGE = 2703205, Nome = "Igreja Nova" },
            new Municipio { CodigoIBGE = 2703304, Nome = "Inhapi" },
            new Municipio { CodigoIBGE = 2703403, Nome = "Jacaré dos Homens" },
            new Municipio { CodigoIBGE = 2703502, Nome = "Jacuípe" },
            new Municipio { CodigoIBGE = 2703601, Nome = "Japaratinga" },
            new Municipio { CodigoIBGE = 2703700, Nome = "Jaramataia" },
            new Municipio { CodigoIBGE = 2703759, Nome = "Jequiá da Praia" },
            new Municipio { CodigoIBGE = 2703809, Nome = "Joaquim Gomes" },
            new Municipio { CodigoIBGE = 2703908, Nome = "Jundiá" },
            new Municipio { CodigoIBGE = 2704005, Nome = "Junqueiro" },
            new Municipio { CodigoIBGE = 2704104, Nome = "Lagoa da Canoa" },
            new Municipio { CodigoIBGE = 2704203, Nome = "Limoeiro de Anadia" },
            new Municipio { CodigoIBGE = 2704302, Nome = "Maceió" },
            new Municipio { CodigoIBGE = 2704401, Nome = "Major Isidoro" },
            new Municipio { CodigoIBGE = 2704500, Nome = "Maragogi" },
            new Municipio { CodigoIBGE = 2704609, Nome = "Maravilha" },
            new Municipio { CodigoIBGE = 2704708, Nome = "Marechal Deodoro" },
            new Municipio { CodigoIBGE = 2704807, Nome = "Maribondo" },
            new Municipio { CodigoIBGE = 2704906, Nome = "Mar Vermelho" },
            new Municipio { CodigoIBGE = 2705002, Nome = "Mata Grande" },
            new Municipio { CodigoIBGE = 2705101, Nome = "Matriz de Camaragibe" },
            new Municipio { CodigoIBGE = 2705200, Nome = "Messias" },
            new Municipio { CodigoIBGE = 2705309, Nome = "Minador do Negrão" },
            new Municipio { CodigoIBGE = 2705408, Nome = "Monteirópolis" },
            new Municipio { CodigoIBGE = 2705507, Nome = "Murici" },
            new Municipio { CodigoIBGE = 2705606, Nome = "Novo Lino" },
            new Municipio { CodigoIBGE = 2705705, Nome = "Olho d'Água das Flores" },
            new Municipio { CodigoIBGE = 2705804, Nome = "Olho d'Água do Casado" },
            new Municipio { CodigoIBGE = 2705903, Nome = "Olho d'Água Grande" },
            new Municipio { CodigoIBGE = 2706000, Nome = "Olivença" },
            new Municipio { CodigoIBGE = 2706109, Nome = "Ouro Branco" },
            new Municipio { CodigoIBGE = 2706208, Nome = "Palestina" },
            new Municipio { CodigoIBGE = 2706307, Nome = "Palmeira dos Índios" },
            new Municipio { CodigoIBGE = 2706406, Nome = "Pão de Açúcar" },
            new Municipio { CodigoIBGE = 2706422, Nome = "Pariconha" },
            new Municipio { CodigoIBGE = 2706448, Nome = "Paripueira" },
            new Municipio { CodigoIBGE = 2706505, Nome = "Passo de Camaragibe" },
            new Municipio { CodigoIBGE = 2706604, Nome = "Paulo Jacinto" },
            new Municipio { CodigoIBGE = 2706703, Nome = "Penedo" },
            new Municipio { CodigoIBGE = 2706802, Nome = "Piaçabuçu" },
            new Municipio { CodigoIBGE = 2706901, Nome = "Pilar" },
            new Municipio { CodigoIBGE = 2707008, Nome = "Pindoba" },
            new Municipio { CodigoIBGE = 2707107, Nome = "Piranhas" },
            new Municipio { CodigoIBGE = 2707206, Nome = "Poço das Trincheiras" },
            new Municipio { CodigoIBGE = 2707305, Nome = "Porto Calvo" },
            new Municipio { CodigoIBGE = 2707404, Nome = "Porto de Pedras" },
            new Municipio { CodigoIBGE = 2707503, Nome = "Porto Real do Colégio" },
            new Municipio { CodigoIBGE = 2707602, Nome = "Quebrangulo" },
            new Municipio { CodigoIBGE = 2707701, Nome = "Rio Largo" },
            new Municipio { CodigoIBGE = 2707800, Nome = "Roteiro" },
            new Municipio { CodigoIBGE = 2707909, Nome = "Santa Luzia do Norte" },
            new Municipio { CodigoIBGE = 2708006, Nome = "Santana do Ipanema" },
            new Municipio { CodigoIBGE = 2708105, Nome = "Santana do Mundaú" },
            new Municipio { CodigoIBGE = 2708204, Nome = "São Brás" },
            new Municipio { CodigoIBGE = 2708303, Nome = "São José da Laje" },
            new Municipio { CodigoIBGE = 2708402, Nome = "São José da Tapera" },
            new Municipio { CodigoIBGE = 2708501, Nome = "São Luís do Quitunde" },
            new Municipio { CodigoIBGE = 2708600, Nome = "São Miguel dos Campos" },
            new Municipio { CodigoIBGE = 2708709, Nome = "São Miguel dos Milagres" },
            new Municipio { CodigoIBGE = 2708808, Nome = "São Sebastião" },
            new Municipio { CodigoIBGE = 2708907, Nome = "Satuba" },
            new Municipio { CodigoIBGE = 2708956, Nome = "Senador Rui Palmeira" },
            new Municipio { CodigoIBGE = 2709004, Nome = "Tanque d'Arca" },
            new Municipio { CodigoIBGE = 2709103, Nome = "Taquarana" },
            new Municipio { CodigoIBGE = 2709152, Nome = "Teotônio Vilela" },
            new Municipio { CodigoIBGE = 2709202, Nome = "Traipu" },
            new Municipio { CodigoIBGE = 2709301, Nome = "União dos Palmares" },
            new Municipio { CodigoIBGE = 2709400, Nome = "Viçosa" }
        };
    }
}